CREATE TABLE SQL_LINEAGE_TEMP_TABLE as
SELECT a.*, 
b.FLS_CD, 
b.FLS_AGENCY_CD,
TO_CHAR(TO_DATE(c.PROPOSAL_RECEIVED_DT),'DD/MM/YYYY') PROPOSAL_DT
FROM TEMP_a a
LEFT JOIN temp_schema_3.POS_APP_DISTRIBUTOR_DTLS b
ON a.POS_APPLICATION_RK = b.POS_APPLICATION_RK
LEFT JOIN temp_schema_3.POS_APPLICATION c
ON a.POS_APPLICATION_RK = c.POS_APPLICATION_RK;